### ISSUE TITLE
missing stub for me.time.rate

### ISSUE THREAD

**Issue by naychrist** [optexture/td-components#1]
Hi there, thanks so much for this [medium article](https://medium.com/@tekt/improving-python-development-for-touchdesigner-5f60d6bafe31) and for maintaining the stubs. Super helpful. Just a note that I notice `me.time.rate` still displays as an error as `me` can't be found - although that's the only missing thing I've come across so far! Hopefully TD will help make these kinds of workflows smoother in future.

**Comment by t3kt** [comment]
This issue has been fixed for a little while. Sorry for the delay.

**Comment by naychrist** [comment]
hi there, thanks for that, I just replaced the stub files but still get errors along the lines of 'Unresolved reference 'me' ' for any similar func call. Is there anything else that needs to be done other than including '_stubs' and adding that header to files as per medium article? Or is this just something we need to put up with for the 'me' convenience method unless we typecast it or something? Any advice appreciated.

**Comment by t3kt** [comment]
Do you have an example of a script that shows this error?

As far as I know, `me` is only available in the context of parameter expressions. Are there times you would use it in an actual script in a DAT?

**Comment by naychrist** [comment]
It works in scripts for things like `me.store('lastId', newId)`, `me.fetch('lastId')`, `me.time.rate` but shows the error. I haven't needed for much else yet but haven't done too much with TD yet.

the store is useful as an alternative to python global variables, which would otherwise be reset each type script is triggered

**Comment by t3kt** [comment]
Huh. I don't think I've ever used that. Generally I try to do things like that on a parent COMP instead. Anyways, I've added a definition for `me` that uses `_AnyOpT` which is treated as being any of several different types of OPs (DAT, SOP, CHOP, COMP)

**Comment by naychrist** [comment]
awesome, thanks for that
